### ISSUE TITLE
Make extension visible to people at the FT

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#102]
Currently, our extension is loaded into the Chrome developer's dashboard, but is not visible for people to install, despite being published. It may be the case that ITSD still have to approve the ext. before it's available to staff internally.

**Comment by AdaRoseCannon** [comment]
It appears to be visible now, closing.

![image](https://cloud.githubusercontent.com/assets/4225330/13128258/582024ae-d589-11e5-8fb8-a9d3716b8ec3.png)
