### ISSUE TITLE
Create Demo Checklist

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#117]
"So there won't be a faff"

**Comment by JakeChampion** [comment]
- Share screen on hangouts
- Hide the sharing bar at the bottom of the screen
- If possible, have all pages preloaded
- Don't do any debugging in the demo

P.S. I think this issue should live in a different repository

**Comment by JakeChampion** [comment]
Closing in favour of - https://github.com/Financial-Times/ft-labs/issues/12
