### ISSUE TITLE
Decide what to do with the extension after we've done with it

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#118]
Explore inert state.

**Comment by JakeChampion** [comment]
I think the simplest solution is what Luke suggested. Release a new version of the extension which has no functionality and could display a dialogue window saying "The experiment is over, thanks for taking part!".

**Comment by AdaRoseCannon** [comment]
It would be nice if the back end was sable enough that we could leave it indefinitely.

But I like the message of saying the experiment is over. Maybe add a contact back or a link to a feedback form. Enough positive feedback might prompt a team to be assigned to look after it.

**Comment by seanmtracey** [comment]
Just noting that it's entirely possible to have the Chrome extension [uninstall itself](https://developer.chrome.com/extensions/management#method-uninstallSelf). If we wanted to blitz any trace of the extension some point down the line, this seems like the most complete option (and doesn't require any user interaction.)

**Comment by AdaRoseCannon** [comment]
I like that!!

**Comment by JakeChampion** [comment]
I like that approach, closing this issue as an approach has been agreed upon, let's make an issue to create this functionality behind an environment variable, that way we can uninstall all extensions without requiring commiting any code.
