### ISSUE TITLE
Enable chrome extension to uninstall itself based on the response from the server

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#126]
Have an environment variable which when set changes the response the server gives through it's api endpoint, the response should inform the consumer (chrome extension) to uninstall itself as the project is now over.

**Comment by seanmtracey** [comment]
This relates to issue #118 

We'd have to make sure that ITSD have disabled the auto-install of the extension on FT Chrome devices. If we're right in our suspicions that ITSD disabling the extension doesn't automatically delete it from the managed systems, a situation could arise where:
1. We tell the extension to uninstall itself
2. ITSD registers that the extension is not on the device and reinstalls
3. The extension calls our server
4. See 1.

**Comment by JakeChampion** [comment]
Resolved via #127
