### ISSUE TITLE
Get ITSD to install the Chrome Extension on FT machines

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#63]

**Comment by JakeChampion** [comment]
@seanmtracey Could you update this issue with any insights you have please?

**Comment by seanmtracey** [comment]
As of now, have contacted ITSD about the possibility of installing the extension across the FT, but have yet to hear anything more on the matter. Will be chasing them on it before todays sprint review. It should also be noted that a number of team members are uncertain that a blanket install across the company is the best way to go about getting this in front of people.

**Comment by JakeChampion** [comment]
I agree about not pushing this in front of all FT Staff. To test the hypothesis, this only needs to go out to a number of FT product influencers such as Product Owners, Project Managers etc. If the hypothesis is proven true and if we want to have this project live on as a fully supported application, that is when I think we should have conversations around if we roll it out automatically and how we would go about doing that.

**Comment by seanmtracey** [comment]
Have spoken with Chris Fujak about this, entirely possible to deploy across the FT and to a subset of FT people. There is a concern that the extension would persist across the devices we install it on if we later decided to remove it from the FT internal Chrome store, which may require a manual uninstall.

**Comment by JakeChampion** [comment]
In light of the recent ITSD Chrome extension rollout, I don't think we should do this
