### ISSUE TITLE
Update the UI of the widget in line with the prototype

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#67]
Here is the prototype:

![screen shot 2016-02-08 at 18 23 08](https://cloud.githubusercontent.com/assets/1569131/12894830/0aadb0b4-ce91-11e5-9ba0-2fd256bc324a.png)

**Comment by AdaRoseCannon** [comment]
Fixed by #69 - which adds the a11y box and puts the layout more inline with the mockup.
