### ISSUE TITLE
Investigate Pagespeed + S3O

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#74]
#### Issue

Luke Blaney says: "Sites behind s3o always get a "This page makes too many requests" from Google PageSpeed due to google's login form.  (I think most of the insights will suffer from the same problem)"

An example would be the [FT Healthcheck](http://healthcheck.ft.com/service/8c28d9e07c28eaf34af0b195fb454df4/6e2061ba8b012f85628024ca0ae878be)

**Comment by JakeChampion** [comment]
For that text to appear, the page must have 10 or more requests being made. Perhaps this number is too small?

**Comment by JakeChampion** [comment]
Resolved via https://github.com/ftlabs/perf-widget/pull/81
