### ISSUE TITLE
Don't drop tables on deploy

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#76]
#### Issue

Currently, with every deploy to a local/live/test server, we drop the tables in our database so that we can recreate them with any changes in the structure. While this is a nice, convenient way to ensure that we have consistent table structure across our instances, regrettably, we lose all of the information/history about every page that we've ever perfed (perf'd, perf-d?). 
#### Solution

While not an issue for local/test instances that information would be useful to keep once on our live servers. 
#### Proposed Solution/s
1. Agree to not change our current table structure and only run the database destruction+creation code when we're not on a production server
2. Come up with a smarter way to migrate table data across different data structures

**Comment by JakeChampion** [comment]
I vote for option 2.

**Comment by JakeChampion** [comment]
We need to do this prior to the next deploy from Test to Live

**Comment by seanmtracey** [comment]
Closed by #134
