### ISSUE TITLE
how can we track usage of the perf-widget?

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#77]
We have the install count on the Chrome web store, but we don't have much in the way of metrics for usage. Is this something we can infer from the number of requests to our server, could we (should we?) identify individuals using our service as well just requests over time?

**Comment by JakeChampion** [comment]
Is this something we want to be doing? What is usage good for if we are loading the widget automatically on websites and have the extension rolled out to all FT Staff Chrome browsers?

**Comment by seanmtracey** [comment]
We do load the widget automatically, but it would be useful to have some sort of measure when people actively use the widget, say, on our competitors pages, or on FT services whose domains don't match the *.ft.com pattern. I do concede that this may be a very tricky thing to track.

**Comment by JakeChampion** [comment]
Whys is this useful to have? We could have a page similar in design to https://cdn.polyfill.io/v2/docs/usage

**Comment by railsagainstignorance** [comment]
Becauses we need to know, somehow, if this thing is a thing.
The perf usage page is a fine idea. Gets my vote.

**Comment by railsagainstignorance** [comment]
we will track by
- o tracking for
  -- widget interactions
- extension 
  -- enabled/disabled 
  -- installs
