### ISSUE TITLE
Are we logging how long it takes to generate an insight...

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#78]
...per page/domain/provider?

**Comment by JakeChampion** [comment]
Nope, should we do this?

**Comment by seanmtracey** [comment]
Always useful to have metrics on this sort of thing. Could be useful in identifying bottlenecks in our response times and trying to decide whether or not an insight is valuable enough to warrant the time it takes to obtain it.

**Comment by JakeChampion** [comment]
Closing this issue, will create an issue to track implementing this feature
