### ISSUE TITLE
Investigate speedcurve to replace other performance metrics.

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#85]
We have a speedcurve account that is configured to access next.ft.com services, and could (presumably) be configured to access other FT services behind opt-ins and walls. If we replace our current performance insight providers with the internal ones, we can surface more relevant insights to our p-widge users.

**Comment by JakeChampion** [comment]
I've spoken to Patrick Hamann about this and the conclusion is that the account they have does not provide enough resources for perf-widget.
