### ISSUE TITLE
Don't swallow redirects

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#86]
If we're getting redirected, don't show perf metrics for the page we're on, but still surface the security and accessibility insights.

**Comment by JakeChampion** [comment]
I think the solution to this issue is partially incorrect. Below is what I think is a better solution to the issue.

If we're being redirected we should not show any metrics that are gathered by the server, we should only show metrics gathered from the client-side (the extension).

**Comment by seanmtracey** [comment]
That sounds like a sane solution. Right now, the only insights that we would surface would be a11y and domain insights.

**Comment by JakeChampion** [comment]
I believe in the meeting on Friday Luke mentioned he is not in favour of domain insights being provided if the domain has a redirection in place.

**Comment by lucas42** [comment]
No, I think domain level things like SSL Labs are fine, because they won't follow HTTP redirects.

**Comment by JakeChampion** [comment]
Yup, we went back at checked the meeting notes and saw that you mentioned running SSL Labs for sites which redirect. This work has been done in PR https://github.com/ftlabs/perf-widget/pull/96.
