### ISSUE TITLE
Don't show the insights on personalised pages

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#87]
Content that's been manipulated according the users preferences may not return results that actually align with what's being displayed. We should not surface these insights, but instead alert the user that the page is customised to their usage, and that we cannot provide reliable insight.

**Comment by JakeChampion** [comment]
How do we know if a page is personalised?

**Comment by AdaRoseCannon** [comment]
This may be utter craziness: 

Super strict: check a hash of document.body.textContent to see if the text is different
OR
Kinda strict: produce a map of the DOM nodes/ids/classes/heirarchies and compare that

**Comment by seanmtracey** [comment]
I don't think that would be wise. Don't we run the risk of supressing insights on any page that has AJAX functionality?

**Comment by JakeChampion** [comment]
As well as pages which have adverts or simply pages which change their content (such as a news index page).
