### ISSUE TITLE
"Don't show me this on this domain"

### ISSUE THREAD

**Issue by seanmtracey** [ftlabs/perf-widget#88]
There may be circumstances, where a URL matches patterns for URLs that we think we should check, but the user may not, in fact, want to see - stash for example.

The close button hides the dialog for that page, but a reload or navigation to another page on the domain will cause it to reappear. Perhaps we could have a "I don't want to see this" button that persists across the domain and supresses the widget entirely.

**Comment by AdaRoseCannon** [comment]
Fixed by #93
