### ISSUE TITLE
add o tracking for widget interactions

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/perf-widget#89]
impl of an answer in #77

**Comment by AdaRoseCannon** [comment]
https://docs.google.com/document/d/1Y30obt8AeeohLvTA748sXjYYwwSboKOmdxhhGMDxQys/edit#

**Comment by JakeChampion** [comment]
This should probably use the same UUID that is going to be used for the extension itself -- discussed in #90

**Comment by JakeChampion** [comment]
https://github.com/Financial-Times/o-tracking/blob/fca7fb37e256c28171157ebfcc00c73951460faf/src/javascript/core.js#L28
