### ISSUE TITLE
in extension,  track count of enabled/disabled state over time

### ISSUE THREAD

**Issue by railsagainstignorance** [ftlabs/perf-widget#90]
impl of answer in #77

**Comment by seanmtracey** [comment]
How would this work? Do we have every every extension report its state periodically? Do we track the state of the extension against an identifiable user ID? Is that wise?

**Comment by JakeChampion** [comment]
To track how many user's have the extension installed:
We could use https://developer.chrome.com/apps/identity#type-AccountInfo

Or we could generate a UUID and store that in the extensions storage

**Comment by seanmtracey** [comment]
The built-in account info thing gets my vote
