### ISSUE TITLE
Bucket similar pages together to ease the load on insight providers

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#92]
Running synthetic tests for every page being visited on FT products may not be the best approach, we should look into bucketing similar pages together. For example, Next FT have different types of articles, we could bucket these together and only run synthetic tests for one page of each type instead of running the tests against every page of any type.

This is related to #85.

**Comment by JakeChampion** [comment]
I recommend talking to @patrickhamann about this

**Comment by lucas42** [comment]
I think you may lose valuable data if you do this.  For example, if articles which have a video embed are substantially slower to load, there'll be no feedback about this if they're lumped in with non-video articles.  (The same applies to any sort of asset that an article may have and all combinations of assets).

Also, you'll need to be very careful with the wording to prevent misleading anyone.

**Comment by JakeChampion** [comment]
@lucas42 Agree completely.

I think we should look to have a meeting with Patrick and see what we can conclude.
