### ISSUE TITLE
Contrast insight wording

### ISSUE THREAD

**Issue by JakeChampion** [ftlabs/perf-widget#98]
> I think the wording on the accessibility insight could do with some work.  I have no idea what it means by "good contrast".  Also, I don't know how percentage of text on a page can be greater in magnitude than 100%.  Finally, I don't understand negative percentages for things that don't have a defined baseline for comparison.

![](https://cloud.githubusercontent.com/assets/1569131/13052145/20ca95ba-d3f5-11e5-9d89-fd0852ac6b6d.png)

**Comment by AdaRoseCannon** [comment]
Url: healthcheck.ft.com

**Comment by JakeChampion** [comment]
Another: http://dashing.internal.ft.com/blue

**Comment by AdaRoseCannon** [comment]
Maths fixed by: #99
